#!/bin/bash

# Copyright (C) 2014 - Cyril Peponnet cyril@peponnet.fr
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; version 2 of the License.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston,
# MA  02110-1301, USA.  A copy of the GNU General Public License is
# also available at http://www.gnu.org/copyleft/gpl.html.

# Requires: sudo livecd-creator, sudo setenforce, ksflatten

ME=$(basename "$0")
warn() { printf '%s: %s\n' "$ME" "$*" >&2; }
die() { warn "$*"; exit 1; }

RECIPE=${RECIPE:-$1}
if [ -z "$RECIPE" -o "$RECIPE" != "${RECIPE#-}" ]; then
    die "Usage: $ME [<recipe.ks>]"
fi
LABEL=$(basename "$RECIPE")
LABEL=${LABEL%%.ks}

ANSOS_CACHE_DIR="${ANSOS_CACHE_DIR:-$HOME/ansos-cache}"
ARCH=$(rpm --eval '%{_arch}')
ANSOS_TMP="$ANSOS_CACHE_DIR/ANSOS-creator-$ARCH-tmp"
mkdir -p "$ANSOS_TMP"
ANSOS_KS="$ANSOS_TMP/$LABEL.ks"

if pgrep -xl nscd; then
    die "Please stop nscd first"
fi

rm -f "$ANSOS_KS" "$ANSOS_KS.tmp"
# combine recipe includes
ksflatten --config "$RECIPE" --output "$ANSOS_KS.tmp"
# XXX broken ksflatten leaves %include
sed -i 's/^%include /#&/' "$ANSOS_KS.tmp"

# adding our local repo
if [ -n "$ANSOS_LOCAL_REPO" ]; then
    echo "repo --name=local --baseurl=$ANSOS_LOCAL_REPO" >> "$ANSOS_KS"
fi

# parsing our local repo and append package to archipel-pkgs.ks
find $ANSOS_LOCAL_REPO -iname *.rpm -exec rpm -qp --qf "%{NAME}\n" {} \; >> "$ANSOS_KS"

# adding any extra repo
if [ -n "$ANSOS_EXTRA_REPO" ]; then
  for repo in $ANSOS_EXTRA_REPO; do
    echo "repo --name=local --baseurl=$repo" >> "$ANSOS_KS"
  done
fi

# adding any extra packages
if [ -n "$ANSOS_EXTRA_PKGS" ]; then
  for pkg in $ANSOS_EXTRA_PKGS; do
    echo "pkg" >> "$ANSOS_KS"
  done
fi

cat "$ANSOS_KS.tmp" >> "$ANSOS_KS"
rm -f "$ANSOS_KS.tmp"

mkdir -p "$ANSOS_CACHE_DIR/yum-$ARCH"
SELINUX_ENFORCING=$(/usr/sbin/getenforce)
case "$SELINUX_ENFORCING" in
    Enforcing) sudo /usr/sbin/setenforce Permissive ;;
    Permissive) ;;
    *) if grep -q '^selinux --disabled' "$ANSOS_KS";
           then
               warn "WARNING: SELinux disabled in kickstart"
           else
               die "ERROR: SELinux enabled in kickstart, \
               but disabled on the build machine"
       fi ;;
esac
sudo livecd-creator -c "$ANSOS_KS" -f "$LABEL" \
    --tmpdir="$ANSOS_TMP" \
    --cache="$ANSOS_CACHE_DIR/yum-$ARCH"
if [ "$SELINUX_ENFORCING" = Enforcing ]; then
    sudo /usr/sbin/setenforce Enforcing
fi
